version: "3.8"

services:
  frontend:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    restart: always
